// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unima.Dal.Context;

#nullable disable

namespace Unima.Dal.Migrations.UnimaDb
{
    [DbContext(typeof(UnimaDbContext))]
    [Migration("20250129112529_Add_Supports_Table")]
    partial class Add_Supports_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unima.Dal.Entities.Models.Support.Support", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelegramAccountURLId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Supports");
                });
#pragma warning restore 612, 618
        }
    }
}
